# Basic set up for three package managers

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/Demo-Start"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/Demo-Database"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/Demo-PKI"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/Demo-Authentication"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/Demo-Authentication/Vault-SpringUser-Plugin"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
