apiVersion: v1
kind: Secret
metadata:
  name: {{ include "Backend.fullname" . }}
type: Opaque
stringData:
  USERNAME: {{ required "Must provide username for Rest-Service" .Values.backend.username }}
  PASSWORD: {{ required "Must provide password for Rest-Service" .Values.backend.password }}
  DATABASE_URI: {{ required "Must provide url for the database" .Values.backend.db.url }}
