apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "Frontend.fullname" . }}
data:
  BACKEND_URL: {{ .Values.frontend.backend_url | default "http://backend" }}
  VAULT_URI: {{ required "Must provide URL to active Vault" .Values.vault.hostname }}
  VAULT_ENABLED: "true"
