apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "Backend.fullname" . }}
data:
  MONGODB_HOST: {{ required "Must provide host for the database" .Values.backend.db.hostname }}
  VAULT_URI: {{ required "Must provide URL to active Vault" .Values.vault.hostname }}
  VAULT_ENABLED: "true"
