apiVersion: v1
kind: Secret
metadata:
  name: {{ include "Frontend.fullname" . }}
type: Opaque
stringData:
  USERNAME: {{ required "Must provide username for Rest-Service" .Values.frontend.username }}
  PASSWORD: {{ required "Must provide password for Rest-Service" .Values.frontend.password }}


