services:
  frontend:
    image: dynamic-credentials/frontend
    environment:
      - "BACKEND_URL=http://backend:8080"
    networks:
      - inner
    ports:
      - "8080:8080"
    depends_on:
      - backend
  backend:
    image: dynamic-credentials/backend
    environment:
      - "DATABASE_URI=mongodb://database"
    networks:
      - inner
    ports:
      - "8088:8080"
  database:
    image: mongo:6.0.1-focal
    networks:
      - inner
    hostname: database

networks:
  inner: {}
