# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'Demo-Start/IntegrationTest'
#      - name: Build Demo-Start
#        working-directory: Demo-Start
#        run: mvn install
#      - name: Start Demo-Start
#        working-directory: Demo-Start
#        run: docker-compose up -d
#      - name: Test Demo-Start
#        working-directory: Demo-Start/IntegrationTest
#        run: npm install && npm run cy:run
#      - name: Stop Demo-Start
#        working-directory: Demo-Start
#        run: docker-compose down && docker-compose rm -f
#      - name: Build Demo-Database
#        working-directory: Demo-Database
#        run: mvn install
#      - name: Start Demo-Database
#        working-directory: Demo-Database
#        run: docker-compose up -d
#      - name: Test Demo-Database
#        working-directory: Demo-Database/IntegrationTest
#        run: sleep 10 && npm install && npm run cy:run
#      - name: Stop Demo-Database
#        working-directory: Demo-Database
#        run: docker-compose down && docker-compose rm -f
      - name: Build Demo-PKI
        working-directory: Demo-PKI
        run: mvn install
      - name: Start Demo-PKI vault
        working-directory: Demo-PKI
        run: docker-compose up -d vault vault_provisioner backend
      - name: show PKI token
        run: timeout 60s sh -c 'until curl http://localhost:8200/v1/pki/cert/ca; do sleep 1; done'
      - name: retrieve PKI token
        working-directory: Demo-PKI
        run: echo "TRUSTED_CERTIFICATE=`curl http://localhost:8200/v1/pki/cert/ca | jq .data.certificate | sed 's/\\n/\n/g'| sed -e's/\"//'`" >> $GITHUB_ENV
#      - name: Start Demo-PKI frontend
#        working-directory: Demo-PKI
#        run: docker-compose up -d frontend
      - name: install NPM dependencies
        working-directory: Demo-PKI/IntegrationTest
        run: npm install
      - name: Test Demo-PKI
        uses: cypress-io/github-action@v4
        with:
          start: docker-compose up -d frontend
          wait-on: http://localhost:8080/actuator/health/liveness
          wait-on-timeout: 120
          working-directory: Demo-PKI/IntegrationTest
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Show logs
        if: failure()
        run: docker-compose logs
      - name: Stop Demo-PKI
        working-directory: Demo-PKI
        run: docker-compose down && docker-compose rm -f
#      - name: Build Demo-Authentication
#        working-directory: Demo-Authentication
#        run: mvn install
#      - name: Build Vault Plugin
#        working-directory: Demo-Authentication/Vault-SpringUser-Plugin
#        run: make build
#      - name: Start Demo-Authentication
#        working-directory: Demo-Authentication
#        run: docker-compose up -d
#      - name: Test Demo-Authentication
#        working-directory: Demo-Authentication/IntegrationTest
#        run: npm install && npm run cy:run
#      - name: Stop Demo-Authentication
#        working-directory: Demo-Authentication
#        run: docker-compose down && docker-compose rm -f

