# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Demo-Start
        working-directory: Demo-Start
        run: mvn package
      - name: Build Demo-Database
        working-directory: Demo-Database
        run: mvn package
      - name: Build Demo-PKI
        working-directory: Demo-PKI
        run: mvn package
      - name: Build Demo-Authentication
        working-directory: Demo-Authentication
        run: mvn package
      - name: Build Vault Plugin
        working-directory: Demo-Authentication/Vault-SpringUser-Plugin
        run: make
